# Arquivo de configuração do BD
# Para criar banco use rake db:create

#-- CONFIGURAÇÕES "PADRÃO"
default: &default
  adapter: postgresql
  encoding: SQL_ASCII
  # Define a quantidade de conexões simultâneas no banco, para ler mais:
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

#-- BANCO "DESENVOLVIMENTO"
development:
  <<: *default
  database: dev_db_evegano  # Nome do banco
  adapter: postgresql       # SQL Adapter usado
  encoding: SQL_ASCII       # Codificação usada
  pool: 5                   # Número de conexões simultâneas
    
  #username: ubuntu
  #password: equipeone11

  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user that initialized the database.
  #username: workspace

  # The password associated with the postgres role (username).
  #password:

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice


#-- BANCO DE TESTE
# ATENÇÃO: O banco de dados definido como "teste" será apagado e
# regenerado da sua database de desenvolvimento sompre que você rodar um "rake".
# Nunca use esse banco como m mesmo de "desenvolvimento" ou "produção".
test: &test
  <<: *default

  database: test_db_evegano
  adapter: postgresql
  encoding: SQL_ASCII
  pool: 5
  #username: ubuntu
  #password: equipeone11
  
# Com o config/secrets.yml, você não guarada informações sensíveis,
# como a senha do teu banco de dados no código fonte. Se em algum momento teu
# código for visto pro qualquer um, você perdeu sua segurança.
#
# Porém, o próprio rails não saber que no Rails 5.2.1 o secrets.yml foi descontinuado
# e substituido por uns lances de credenciais. Lê mais sobre isso aqui:
# https://www.engineyard.com/blog/rails-encrypted-credentials-on-rails-5.2
#

#-- BANCO DE PRODUÇÃO (HEROKU)
production:
  <<: *default
  database: evegano_production
  username: workspace
  password: <%= ENV['WORKSPACE_DATABASE_PASSWORD'] %>
  
# No Heroku ou outras plataformas provedoreas, voceê pode acessar uma URL
# dispoível numa variavel do ambiente. Por exemplo:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
  
#-- BANCO DO CUCUMBER
cucumber:
  <<: *test
